title: BohrLabs
description: Notes, experiments and engineering insights.
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme

collections:
  blog:
    output: true
    permalink: /blog/:name/
